#include "onyx/core/api.hpp"
#define VMA_NULLABLE
#define VMA_NOT_NULL
KIT_WARNING_IGNORE_PUSH
KIT_GCC_WARNING_IGNORE("-Wunused-parameter")
KIT_GCC_WARNING_IGNORE("-Wunused-variable")
KIT_GCC_WARNING_IGNORE("-Wunused-function")
KIT_GCC_WARNING_IGNORE("-Wmissing-field-initializers")
KIT_CLANG_WARNING_IGNORE("-Wunused-parameter")
KIT_CLANG_WARNING_IGNORE("-Wunused-variable")
KIT_CLANG_WARNING_IGNORE("-Wunused-function")
KIT_CLANG_WARNING_IGNORE("-Wmissing-field-initializers")
KIT_MSVC_WARNING_IGNORE(4100)
KIT_MSVC_WARNING_IGNORE(4189)
KIT_MSVC_WARNING_IGNORE(4505)
KIT_MSVC_WARNING_IGNORE(4351)
#include <vk_mem_alloc.h>
KIT_WARNING_IGNORE_POP