#pragma once

#define ONYX_ASSET_TYPE_BITS 3U
#define ONYX_ASSET_POOL_BITS 8U

#define ONYX_ASSET_TYPE_SHIFT (32U - ONYX_ASSET_TYPE_BITS)
#define ONYX_ASSET_POOL_SHIFT (32U - ONYX_ASSET_TYPE_BITS - ONYX_ASSET_POOL_BITS)

#define ONYX_ASSET_BITS ONYX_ASSET_POOL_SHIFT

#define ONYX_ASSET_TYPE_MASK (0xFFFFFFFFU << ONYX_ASSET_TYPE_SHIFT)
#define ONYX_ASSET_POOL_MASK (0xFFFFFFFFU << ONYX_ASSET_POOL_SHIFT)
#define ONYX_ASSET_POOL_ID_MASK (ONYX_ASSET_POOL_MASK & ~ONYX_ASSET_TYPE_MASK)
#define ONYX_ASSET_ID_MASK ~ONYX_ASSET_POOL_MASK

#define ONYX_MAX_ASSET_POOLS ((1U << ONYX_ASSET_POOL_BITS) - 1U)
#define ONYX_MAX_ASSETS ((1U << ONYX_ASSET_BITS) - 1U) // per pool

#define ONYX_MAX_SAMPLERS 8
#define ONYX_MAX_TEXTURES 1024
#define ONYX_MAX_TEXTURE_MAPS 32

#define ONYX_INSTANCES_BINDING_POINT 0
#define ONYX_BOUNDS_BINDING_POINT 3
#define ONYX_SAMPLERS_BINDING_POINT 1
#define ONYX_TEXTURES_BINDING_POINT 2
#define ONYX_MATERIALS_BINDING_POINT 4

#define ONYX_POINT_LIGHTS_BINDING_POINT 5
#define ONYX_DIRECTIONAL_LIGHTS_BINDING_POINT 6
#define ONYX_SPOT_LIGHTS_BINDING_POINT 11

#define ONYX_POINT_MAPS_BINDING_POINT 8
#define ONYX_DIRECTIONAL_MAPS_BINDING_POINT 9
#define ONYX_SPOT_MAPS_BINDING_POINT 10

#define ONYX_SHADOW_SAMPLER_BINDING_POINT 7
#define ONYX_SHADOW_MAPS_BINDING_POINT 8

#define ONYX_OCCLUSION_MAP_BINDING_POINT 0
#define ONYX_DISTANCE_MAP_BINDING_POINT 1

#define ONYX_MAX_CASCADES 4

#define ONYX_MAX_VIEWS 32
#define ONYX_MAX_ATTACHMENTS (5 * ONYX_MAX_VIEWS)

#define ONYX_POST_PROCESS_COLOR_ATTACHMENTS_BINDING 0
#define ONYX_POST_PROCESS_OUTLINE_ATTACHMENTS_BINDING 1
#define ONYX_POST_PROCESS_STENCIL_ATTACHMENTS_BINDING 2

#define ONYX_MARCH_MODE_POINT_LIGHT 0
#define ONYX_MARCH_MODE_DIRECTIONAL_LIGHT 1

#define ONYX_COMPOSITOR_COLOR_ATTACHMENTS_BINDING 0
