#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <memory>
#include <functional>
#include <chrono>
#include <algorithm>
#include <iostream>
#include <type_traits>
#include <utility>
#include <concepts>
#include <thread>
#include <string_view>
#include <fstream>
#include <cstdlib>
#include <filesystem>
#include <vulkan/vulkan.h>
#include "tkit/preprocessor/system.hpp"
#include "tkit/preprocessor/utils.hpp"
#include "onyx/alias.hpp"
#include "onyx/math.hpp"
