#pragma once

#define ONYX_RESOURCE_WIDTH 32U
#define ONYX_RESOURCE_MASK (~0U)

///

#define ONYX_RESOURCE_TYPE_BITS 4U
#define ONYX_RESOURCE_POOL_BITS 4U

#define ONYX_RESOURCE_TYPE_SHIFT (ONYX_RESOURCE_WIDTH - ONYX_RESOURCE_TYPE_BITS)
#define ONYX_RESOURCE_POOL_SHIFT (ONYX_RESOURCE_WIDTH - ONYX_RESOURCE_TYPE_BITS - ONYX_RESOURCE_POOL_BITS)

#define ONYX_RESOURCE_ID_BITS ONYX_RESOURCE_POOL_SHIFT

#define ONYX_RESOURCE_TYPE_MASK (ONYX_RESOURCE_MASK << ONYX_RESOURCE_TYPE_SHIFT)
#define ONYX_RESOURCE_POOL_MASK (ONYX_RESOURCE_MASK << ONYX_RESOURCE_POOL_SHIFT)
#define ONYX_RESOURCE_POOL_ID_MASK (ONYX_RESOURCE_POOL_MASK & ~ONYX_RESOURCE_TYPE_MASK)
#define ONYX_RESOURCE_ID_MASK ~ONYX_RESOURCE_POOL_MASK

#define ONYX_NULL_RESOURCE_POOL ONYX_RESOURCE_POOL_ID_MASK
#define ONYX_NULL_RESOURCE ONYX_RESOURCE_ID_MASK

#define ONYX_NULL_RESOURCE_POOL_ID (ONYX_RESOURCE_POOL_ID_MASK >> ONYX_RESOURCE_POOL_SHIFT)
#define ONYX_NULL_RESOURCE_ID ONYX_NULL_RESOURCE

#define ONYX_MAX_RESOURCE_TYPES ((1U << ONYX_RESOURCE_TYPE_BITS) - 1U)
#define ONYX_MAX_RESOURCE_POOLS ((1U << ONYX_RESOURCE_POOL_BITS) - 1U)
#define ONYX_MAX_RESOURCE_IDS ((1U << ONYX_RESOURCE_ID_BITS) - 1U) // per pool

///

#define ONYX_SAMPLER_ID_BITS 8U
#define ONYX_TEXTURE_OFFSET_ID_BITS 8U

#define ONYX_SAMPLER_ID_SHIFT (ONYX_RESOURCE_WIDTH - ONYX_SAMPLER_ID_BITS)
#define ONYX_TEXTURE_OFFSET_ID_SHIFT (ONYX_RESOURCE_WIDTH - ONYX_SAMPLER_ID_BITS - ONYX_TEXTURE_OFFSET_ID_BITS)

#define ONYX_TEXTURE_ID_BITS ONYX_TEXTURE_OFFSET_ID_SHIFT

#define ONYX_SAMPLER_ID_MASK (ONYX_RESOURCE_MASK << ONYX_SAMPLER_ID_SHIFT)
#define ONYX_TEXTURE_OFFSET_ID_MASK ((ONYX_RESOURCE_MASK << ONYX_TEXTURE_OFFSET_ID_SHIFT) & ~ONYX_SAMPLER_ID_MASK)
#define ONYX_TEXTURE_ID_MASK ~(ONYX_RESOURCE_MASK << ONYX_TEXTURE_OFFSET_ID_SHIFT)

#define ONYX_MAX_SAMPLER_IDS ((1U << ONYX_SAMPLER_ID_BITS) - 1U)
#define ONYX_MAX_TEXTURE_OFFSET_IDS ((1U << ONYX_TEXTURE_OFFSET_ID_BITS) - 1U)
#define ONYX_MAX_TEXTURE_IDS ((1U << ONYX_TEXTURE_ID_BITS) - 1U)

#define ONYX_NULL_SAMPLER ONYX_SAMPLER_ID_MASK
#define ONYX_NULL_TEXTURE ONYX_TEXTURE_ID_MASK

#define ONYX_NULL_SAMPLER_ID (ONYX_SAMPLER_ID_MASK >> ONYX_SAMPLER_ID_SHIFT)
#define ONYX_NULL_TEXTURE_ID ONYX_NULL_TEXTURE

///

#define ONYX_MAX_DEPTH_COUNTER_VALUE (1U << 24)

#define ONYX_SPOT_LIGHT_NEAR_RANGE_FACTOR 0.05f
#define ONYX_POINT_LIGHT_NEAR_RADIUS_FACTOR 0.05f

// TODO(Isma): These first two interfere with the MAX_*_IDS above. should take minimum of the two
#define ONYX_MAX_SAMPLERS 8
#define ONYX_MAX_TEXTURES 96
#define ONYX_MAX_TEXTURE_MAPS 16
#define ONYX_MAX_RAY_MARCH_AND_OCCLUSION_MAP_SIZE (2 * ONYX_MAX_TEXTURE_MAPS)
#define ONYX_MAX_CASCADES 4
#define ONYX_MAX_VIEWS 32
#define ONYX_MAX_ATTACHMENTS 6

#define ONYX_INSTANCES_BINDING_POINT 0
#define ONYX_SAMPLERS_BINDING_POINT 1
#define ONYX_TEXTURES_BINDING_POINT 2
#define ONYX_TEXTURE_OFFSETS_BINDING_POINT 3
#define ONYX_BOUNDS_BINDING_POINT 4
#define ONYX_MATERIALS_BINDING_POINT 5

#define ONYX_POINT_LIGHTS_BINDING_POINT 6
#define ONYX_DIRECTIONAL_LIGHTS_BINDING_POINT 7

#define ONYX_SHADOW_SAMPLER_BINDING_POINT 8
#define ONYX_SHADOW_COMPARE_SAMPLER_BINDING_POINT 9

#define ONYX_SHADOW_MAPS_BINDING_POINT 10 // for 2D, thats why there is overlap
#define ONYX_SPOT_LIGHTS_BINDING_POINT 10

#define ONYX_POINT_MAPS_BINDING_POINT 11
#define ONYX_DIRECTIONAL_MAPS_BINDING_POINT 12
#define ONYX_SPOT_MAPS_BINDING_POINT 13

#define ONYX_OCCLUSION_MAP_BINDING_POINT 0
#define ONYX_RAY_MARCH_MAP_BINDING_POINT 1

#define ONYX_BLEND_TRANSPARENT_ATTACHMENTS_BINDING 0
#define ONYX_BLEND_REVEALAGE_ATTACHMENTS_BINDING 1

#define ONYX_POST_PROCESS_COLOR_ATTACHMENTS_BINDING 0
#define ONYX_POST_PROCESS_OUTLINE_ATTACHMENTS_BINDING 1
#define ONYX_POST_PROCESS_STENCIL_ATTACHMENTS_BINDING 2

#define ONYX_MARCH_MODE_POINT_LIGHT 0
#define ONYX_MARCH_MODE_DIRECTIONAL_LIGHT 1

#define ONYX_COMPOSITOR_COLOR_ATTACHMENTS_BINDING 0
