#include "onyx/core/pch.hpp"
#include "onyx/platform/input.hpp"
#include "onyx/platform/glfw.hpp"

namespace Onyx
{

const char *ToString(const Key key)
{
    switch (key)
    {
    case Key_Space:
        return "Space";
    case Key_Apostrophe:
        return "Apostrophe";
    case Key_Comma:
        return "Comma";
    case Key_Minus:
        return "Minus";
    case Key_Period:
        return "Period";
    case Key_Slash:
        return "Slash";
    case Key_N0:
        return "N0";
    case Key_N1:
        return "N1";
    case Key_N2:
        return "N2";
    case Key_N3:
        return "N3";
    case Key_N4:
        return "N4";
    case Key_N5:
        return "N5";
    case Key_N6:
        return "N6";
    case Key_N7:
        return "N7";
    case Key_N8:
        return "N8";
    case Key_N9:
        return "N9";
    case Key_Semicolon:
        return "Semicolon";
    case Key_Equal:
        return "Equal";
    case Key_A:
        return "A";
    case Key_B:
        return "B";
    case Key_C:
        return "C";
    case Key_D:
        return "D";
    case Key_E:
        return "E";
    case Key_F:
        return "F";
    case Key_G:
        return "G";
    case Key_H:
        return "H";
    case Key_I:
        return "I";
    case Key_J:
        return "J";
    case Key_K:
        return "K";
    case Key_L:
        return "L";
    case Key_M:
        return "M";
    case Key_N:
        return "N";
    case Key_O:
        return "O";
    case Key_P:
        return "P";
    case Key_Q:
        return "Q";
    case Key_R:
        return "R";
    case Key_S:
        return "S";
    case Key_T:
        return "T";
    case Key_U:
        return "U";
    case Key_V:
        return "V";
    case Key_W:
        return "W";
    case Key_X:
        return "X";
    case Key_Y:
        return "Y";
    case Key_Z:
        return "Z";
    case Key_LeftBracket:
        return "LeftBracket";
    case Key_Backslash:
        return "Backslash";
    case Key_RightBracket:
        return "RightBracket";
    case Key_GraveAccent:
        return "GraveAccent";
    case Key_World_1:
        return "World_1";
    case Key_World_2:
        return "World_2";
    case Key_Escape:
        return "Escape";
    case Key_Enter:
        return "Enter";
    case Key_Tab:
        return "Tab";
    case Key_Backspace:
        return "Backspace";
    case Key_Insert:
        return "Insert";
    case Key_Delete:
        return "Delete";
    case Key_Right:
        return "Right";
    case Key_Left:
        return "Left";
    case Key_Down:
        return "Down";
    case Key_Up:
        return "Up";
    case Key_PageUp:
        return "PageUp";
    case Key_PageDown:
        return "PageDown";
    case Key_Home:
        return "Home";
    case Key_End:
        return "End";
    case Key_CapsLock:
        return "CapsLock";
    case Key_ScrollLock:
        return "ScrollLock";
    case Key_NumLock:
        return "NumLock";
    case Key_PrintScreen:
        return "PrintScreen";
    case Key_Pause:
        return "Pause";
    case Key_F1:
        return "F1";
    case Key_F2:
        return "F2";
    case Key_F3:
        return "F3";
    case Key_F4:
        return "F4";
    case Key_F5:
        return "F5";
    case Key_F6:
        return "F6";
    case Key_F7:
        return "F7";
    case Key_F8:
        return "F8";
    case Key_F9:
        return "F9";
    case Key_F10:
        return "F10";
    case Key_F11:
        return "F11";
    case Key_F12:
        return "F12";
    case Key_F13:
        return "F13";
    case Key_F14:
        return "F14";
    case Key_F15:
        return "F15";
    case Key_F16:
        return "F16";
    case Key_F17:
        return "F17";
    case Key_F18:
        return "F18";
    case Key_F19:
        return "F19";
    case Key_F20:
        return "F20";
    case Key_F21:
        return "F21";
    case Key_F22:
        return "F22";
    case Key_F23:
        return "F23";
    case Key_F24:
        return "F24";
    case Key_F25:
        return "F25";
    case Key_KP_0:
        return "KP_0";
    case Key_KP_1:
        return "KP_1";
    case Key_KP_2:
        return "KP_2";
    case Key_KP_3:
        return "KP_3";
    case Key_KP_4:
        return "KP_4";
    case Key_KP_5:
        return "KP_5";
    case Key_KP_6:
        return "KP_6";
    case Key_KP_7:
        return "KP_7";
    case Key_KP_8:
        return "KP_8";
    case Key_KP_9:
        return "KP_9";
    case Key_KPDecimal:
        return "KPDecimal";
    case Key_KPDivide:
        return "KPDivide";
    case Key_KPMultiply:
        return "KPMultiply";
    case Key_KPSubtract:
        return "KPSubtract";
    case Key_KPAdd:
        return "KPAdd";
    case Key_KPEnter:
        return "KPEnter";
    case Key_KPEqual:
        return "KPEqual";
    case Key_LeftShift:
        return "LeftShift";
    case Key_LeftControl:
        return "LeftControl";
    case Key_LeftAlt:
        return "LeftAlt";
    case Key_LeftSuper:
        return "LeftSuper";
    case Key_RightShift:
        return "RightShift";
    case Key_RightControl:
        return "RightControl";
    case Key_RightAlt:
        return "RightAlt";
    case Key_RightSuper:
        return "RightSuper";
    case Key_Menu:
        return "Menu";
    case Key_None:
        return "None";
    case Key_Count:
        return "Unknown";
    }
    return "Unknown";
}
} // namespace Onyx
